version: "3"
services:
  kvb-rad:
    container_name:  kvb-rad-runner
    image: crowdsalat/kvb-rad:latest
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/kvbbike-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=krautsalat
    ports:
      - "127.0.0.1:9090:8080"
    depends_on:
      - database
  kvb-rad-ui:
    container_name: kvb-rad-ui
    image: crowdsalat/kvb-rad-ui:latest
    restart: always
    ports:
      - "127.0.0.1:9091:8080"
    depends_on:
      - kvb-rad
  database:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=krautsalat
      - POSTGRES_DB=kvbbike-db
    volumes:
      - "kvbrad-db:/var/lib/postgresql"
  routing-api:
    container_name: kvb-rad-graphhopper
    image: crowdsalat/graphhopper-cologne-bike:latest
    restart: always
    ports:
      - "127.0.0.1:8989:8989"
    volumes:
      - "kvbrad-graphhopper:/data"

volumes:
  kvbrad-db:
  kvbrad-graphhopper:
